Add support for decoding non-const enums.
joanllenas/ts.data.json pull request #25
Opened 2020-09-23 00:26 UTC by rhofour

This required bumping up the target to ES2017. The syntax is a little redundant since you need the enum both as a parameter and a template parameter, but it doesn't look like there's a way to get the values of an enum at compile time from the template parameter.

2020-09-23 08:24 UTC, joanllenas commented
Hi @rhofour, thanks for your contribution!
The code part looks perfect, just a couple of minor things. 
- The `target` field in the `tsconfig.ts` file can stay as `'es5'` and everything will work just fine. We need that in order to support ie11.
- Could you please add a documentation section in the readme file following the format of the rest of the file?

Thanks!

2020-09-23 08:25 UTC, joanllenas requested changes
See https://github.com/joanllenas/ts.data.json/pull/25#issuecomment-697213675

2020-09-24 01:32 UTC, rhofour commented
Done. I also bumped the version.

2020-09-24 09:38 UTC, joanllenas approved these changes

2020-09-24 09:38 UTC, merged

2020-09-24 09:49 UTC, joanllenas commented
Thanks! the new version is ready!
https://github.com/joanllenas/ts.data.json/releases/tag/v1.3.0